### PR TITLE
Adapt to panel

### PR DESCRIPTION
**Pull request by ahuang11**
- [ ] Rename repo to `copier-template-panel-extensions`
- [ ] Update README.md to reflect name change
- [ ] Transfer to panel-extensions org
- [ ] Determine if hatch is needed
- [x] Figure out how to compile/structure JSComponent models
- [ ] Add DEVELOPERS_GUIDE
- [ ] Update README.md to take the step by step guide from https://github.com/ahuang11/cookiecutter-hipster-pypackage/blob/main/README.md for easy setup.

### CODE REVIEW

**Comment by philippjfr** [comment]
Works well so far. I would move the package into a `src` directory and remove the `models` directory.

**Comment by ahuang11** [comment]
Hmm I can't seem to use the trusted publisher method to publish to pypi.

**Comment by ahuang11** [comment]
Ahhh finally found it... wasn't a bug--was just me trying to publish to test pypi, while I was setting up the pending publishers in real pypi.

**Comment by ahuang11** [comment]
@hoxbro if you have some time, can you help me take a look at the pixi / CI things? I'm also not sure if hatch is necessary if we have pixi?

**Pull request merged**
